### ISSUE TITLE
Error on build (Unity 2018.2.20f1)

### ISSUE THREAD

**Issue by lb4business** [AlexanderVorobyov/simple-light-probe-placer#1]
Plug-in version: 1.0.12
Errors on Android buid attempt:
Assets/SimpleLightProbePlacer/Scripts/LightProbeGroupControl.cs(34,29): error CS0200: Property or indexer `UnityEngine.LightProbeGroup.probePositions' cannot be assigned to (it is read-only)
Assets/SimpleLightProbePlacer/Scripts/LightProbeGroupControl.cs(61,29): error CS0200: Property or indexer `UnityEngine.LightProbeGroup.probePositions' cannot be assigned to (it is read-only)

**Comment by AlexanderVorobyov** [comment]
Thanks for using my extension, but this repository has been deprecated and I will not introduce any fixies any more.

But to resolve Your issue, You can try to wrap all usages of the `UnityEngine.LightProbeGroup.probePositions` by `UNITY_EDITOR` compile directives.

Example:
```
#if UNITY_EDITOR 
            <-- UnityEngine.LightProbeGroup.probePositions usage -->
#endif
```
